- name: Ensure borg packages installed
  apt:
    name:
      - borgbackup
    state: present
    update_cache: yes

- name: Setup backups directory
  ansible.builtin.file:
    path: /backups
    state: directory
    mode: '0700'

- name: fstab
  ansible.builtin.copy:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/base/disk/fstab_backups' }}"
    dest: '/etc/fstab'
    owner: root
    group: root
    mode: 0600

- name: Sets up cronjob for DDNS
  ansible.builtin.cron:
    name: "Update public DNS records"
    minute: "*/5"
    job: "{{ '/usr/bin/python3 ' + '/root/cron/ddns.py -k ' + lookup('env', 'NAMESILO_API_KEY') }} -d backups.nkontur.com -r '' '*' >> /root/cron/logs/ddns.log 2>&1"
