- name: Ensure mail packages installed
  apt:
    name:
      - postfix
      - dovecot-common 
      - dovecot-imapd
      - opendkim
    state: present
    update_cache: yes

- name: Sync mail files
  copy:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/vps/mail/' + item }}"
    dest: "/etc/{{ item }}"
    directory_mode: 0755
    mode: 0755
  loop:
     - "postfix/"
     - "opendkim.conf"
     - "opendkim/key.table"
     - "opendkim/signing.table"
     - "opendkim/trusted.hosts"
     - "dovecot/"
  register: mail

- name: Sync opendkim files
  copy:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/vps/mail/' + item }}"
    dest: "/etc/{{ item }}"
    directory_mode: 0700
    owner: 121
    group: 127
  loop:
     - "opendkim/keys"
  register: dkim

- name: write dkim private key
  copy:
    content: "{{ lookup('env', 'DKIM_PRIVATE_KEY') | b64decode }}"
    dest: /etc/opendkim/keys/nkontur.com/default.private
    mode: '0700'
    owner: 121
    group: 127
  register: dkim_private

- name: Ensure mail services started and enabled
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
     - postfix
     - opendkim
     - dovecot

- name: Restart mail services if config change
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
     - postfix
     - opendkim
     - dovecot
  when: mail.changed or dkim.changed or dkim_private.changed
