- name: Ensure wireguard installed
  apt:
    name:
      - wireguard
    state: present
    update_cache: yes

- name: Add wireguard config
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/networking/wireguard/vps/wg0.conf' }}"
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0755'
  register: wireguard

- name: Make sure wireguard is started and enabled
  service:
    name: wg-quick@wg0
    state: started
    enabled: yes

- name: Restart wireguard if config change
  service:
    name: wg-quick@wg0
    state: restarted
    enabled: yes
  when: wireguard.changed

- name: Ensure mail packages installed
  apt:
    name:
      - postfix
      - dovecot-common 
      - dovecot-imapd
      - opendkim
    state: present
    update_cache: yes

- name: Sync mail files
  copy:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/vps/mail/' + item + '/' }}"
    dest: "/etc/{{ item }}"
    mode: preserve
  loop:
     - postfix
     - opendkim
     - dovecot
  register: "mail-{{ item }}"

- name: write dkim private key
  copy:
    content: "{{ lookup('env', 'DKIM_PRIVATE_KEY') | b64decode }}"
    dest: /etc/opendkim/keys/nkontur.com/default.private
    mode: 600
  register: dkim

- name: Ensure mail services started and enabled
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
     - postfix
     - opendkim
     - dovecot

- name: Restart mail services if config change
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
     - postfix
     - opendkim
     - dovecot
  when: "mail-{{ item }}.changed"

