# global detect settings (default: shown below)
detect:
  match:
    # save match images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed to consider a result a match
    confidence: 60
    # hours to keep match images until they are deleted
    purge: 168
    # minimum area in pixels to consider a result a match
    min_area: 6000

  unknown:
    # save unknown images
    save: true
    # include base64 encoded string in api results and mqtt messages
    # options: true, false, box
    base64: false
    # minimum confidence needed before classifying a name as unknown
    confidence: 40
    # hours to keep unknown images until they are deleted
    purge: 8
    # minimum area in pixels to keep an unknown result
    min_area: 0
detectors:
  compreface:
    url: https://compreface-fe.iot.lab.nkontur.com
    # recognition api key
    key: {{ lookup('env', 'COMPREFACE_KEY') }}

frigate:
  url: http://frigate.lab.nkontur.com:5000
mqtt:
  host: mqtt.lab.nkontur.com
  username: mosquitto
  password: {{ lookup('env', 'MQTT_PASS') }}
  tls:
    enabled: true
