- name: Ensure proper packages are installed
  apt:
    name:
      - isc-dhcp-server
      - wireguard
      - keepalived
      - netfilter-persistent
      - iptables-persistent
    state: latest
    update_cache: yes

### Configure networking on host
- name: Interfaces config file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/networking/fallback/interfaces.d/vlans' }}"
    dest: '/etc/network/interfaces.d/vlans'
    owner: root
    group: root
    mode: 0600
  register: interfaces

- name: Reload networking daemon to pick up changes
  ansible.builtin.systemd:
    name: networking
    state: restarted
  when: interfaces.changed
  ignore_errors: true

- name: Template the iptables rules file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/networking/iptables/rules.v4' }}"
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0640'
  register: iptables

- name: Restore netfilter rules
  ansible.builtin.command: netfilter-persistent reload
  become: yes
  when: iptables.changed

- name: Populate RNDC key file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/networking/dhcp/rndc.key' }}"
    dest: /etc/dhcp/rndc.key
    owner: root
    group: root
    mode: '0640'

- name: Populate DHCP conf file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/networking/dhcp/dhcpd.conf' }}"
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0640'
  register: dhcp

- name: Restart isc-dhcp-server when the drop-in files change
  service:
    name: isc-dhcp-server
    state: restarted
    enabled: yes
  when: dhcp.changed
  ignore_errors: true

- name: Populate VRRP conf file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/networking/vrrp/keepalived.conf' }}"
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0640'
  register: keepalived

- name: Restart isc-dhcp-server when the drop-in files change
  service:
    name: keepalived
    state: restarted
    enabled: yes
  when: keepalived.changed

