- name: Deploy msmtp configuration
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/base/msmtp/msmtprc' }}"
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: '0600'

- name: Deploy msmtp alias map
  ansible.builtin.copy:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/base/msmtp/aliases' }}"
    dest: /etc/aliases
    owner: root
    group: root
    mode: '0644'

- name: Set msmtp as default MTA
  ansible.builtin.file:
    src: /usr/bin/msmtp
    dest: /usr/sbin/sendmail
    state: link
    force: yes

# borgmatic cron removed — backups use restic now
