services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    image: koenkk/zigbee2mqtt:2.9.1@sha256:574b2bd0dcbb59fae6edbbb81a35b5563291d3825da0225f0078aa5575dac37f
    volumes:
      - {{ docker_persistent_data_path }}/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    networks:
      - zwave
    mem_limit: 256m
    environment:
      - TZ=America/New_York
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  zigbee-config:
    name: zigbee-config
