version: '{{ docker_compose_version }}'
networks:
  internal:
    driver: macvlan
    ipam:
      config:
          - subnet: 10.3.0.0/16
            ip_range: 10.3.128.0/18
            gateway: 10.3.0.1
            aux_addresses:
              router: 10.3.128.1
              vrrp: 10.3.128.2
    driver_opts:
      parent: eth0.3
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "443:80"
    networks:
      internal:
        ipv4_address: {{ fallback_pihole_address }}
    environment:
      TZ: America/New_York
      WEBPASSWORD: {{ lookup('env', 'PIHOLE_PASSWORD') }}
    volumes:
      - /etc/pihole/conf:/etc/pihole
      - /etc/pihole/dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
