
  headway_init:
    image: ghcr.io/headwaymaps/headway-init:latest
    networks:
      iot:
    environment:
      FONT_ARTIFACT_SOURCE_PATH: /bootstrap/fonts.tar
      FONT_ARTIFACT_DEST_PATH: /data/fonts/fonts.tar
      SPRITE_ARTIFACT_SOURCE_PATH: /bootstrap/sprite.tar
      SPRITE_ARTIFACT_DEST_PATH: /data/sprite/sprite.tar
      HEADWAY_PUBLIC_URL: {{ headway_url }}
      HEADWAY_AREA: {{ headway_area }}
    volumes:
      - "{{ docker_persistent_data_path }}/headway/bootstrap:/bootstrap/:ro"
      - "headway_data:/data/:rw"
  valhalla_init:
    image: ghcr.io/headwaymaps/valhalla-init:latest
    networks:
      iot:
    volumes:
      - "valhalla_data:/data/:rw"
      - "{{ docker_persistent_data_path }}/headway/bootstrap:/bootstrap/:ro"
    environment:
      ARTIFACT_SOURCE_PATH: /bootstrap/{{ headway_area }}.valhalla.tar
      ARTIFACT_LOCK: /data/imported
      HEADWAY_PUBLIC_URL: {{ headway_url }}
      HEADWAY_AREA: {{ headway_area }}
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
  otp_init:
    image: ghcr.io/headwaymaps/opentripplanner-init:latest
    networks:
      iot:
    environment:
      ARTIFACT_DEST_PATH: /data/{{ headway_area }}.graph.obj
      ARTIFACT_SOURCE_PATH: /bootstrap/{{ headway_area }}.graph.obj
      HEADWAY_PUBLIC_URL: {{ headway_url }}
      HEADWAY_AREA: {{ headway_area }}
    volumes:
      - "{{ docker_persistent_data_path }}/headway/bootstrap:/bootstrap/:ro"
      - "otp_data:/data/:rw"
  mbtileserver_init:
    image: ghcr.io/headwaymaps/tileserver-init:latest
    networks:
      iot:
    environment:
      MBTILES_ARTIFACT_DEST_PATH: /data/{{ headway_area }}.mbtiles
      MBTILES_ARTIFACT_SOURCE_PATH: /bootstrap/{{ headway_area }}.mbtiles
      NATURAL_EARTH_ARTIFACT_DEST_PATH: /data/natural_earth.mbtiles
      NATURAL_EARTH_ARTIFACT_SOURCE_PATH: /bootstrap/natural_earth.mbtiles
      HEADWAY_PUBLIC_URL: {{ headway_url }}
      HEADWAY_AREA: {{ headway_area }}
    volumes:
      - "{{ docker_persistent_data_path }}/headway/bootstrap:/bootstrap/:ro"
      - "mbtileserver_data:/data/:rw"
  pelias_config_init:
    image: ghcr.io/headwaymaps/pelias-init:latest
    networks:
      iot:
    environment:
      PELIAS_CONFIG_ARTIFACT_SOURCE_PATH: /bootstrap/{{ headway_area }}.pelias.json
      HEADWAY_PUBLIC_URL: {{ headway_url }}
      HEADWAY_AREA: {{ headway_area }}
    command: [ "/bin/bash", "/app/init_config.sh" ]
    volumes:
      - "{{ docker_persistent_data_path }}/headway/bootstrap:/bootstrap/:ro"
      - "pelias_config_data:/config"
  pelias_elastic_init:
    image: ghcr.io/headwaymaps/pelias-init:latest
    networks:
      iot:
    environment:
      ELASTICSEARCH_ARTIFACT_SOURCE_PATH: /bootstrap/{{ headway_area }}.elasticsearch.tar
      HEADWAY_PUBLIC_URL: {{ headway_url }}
      HEADWAY_AREA: {{ headway_area }}
    command: [ "/bin/bash", "/app/init_elastic.sh" ]
    volumes:
      - "{{ docker_persistent_data_path }}/headway/bootstrap:/bootstrap/:ro"
      - "pelias_elasticsearch_data:/usr/share/elasticsearch/data"
  peliasplaceholder_init:
    image: ghcr.io/headwaymaps/pelias-init:latest
    networks:
      iot:
    environment:
      PLACEHOLDER_ARTIFACT_SOURCE_PATH: /bootstrap/{{ headway_area }}.placeholder.tar
      HEADWAY_PUBLIC_URL: {{ headway_url }}
      HEADWAY_AREA: {{ headway_area }}
    command: [ "/bin/bash", "/app/init_placeholder.sh" ]
    volumes:
      - "{{ docker_persistent_data_path }}/headway/bootstrap:/bootstrap/:ro"
      - "pelias_placeholder_data:/data/placeholder"
