mqtt:
  host: {{ mosquitto_address }}
cameras:
  back:
    ffmpeg:
      inputs:
        - path: "rtsp://admin:{{ lookup('env', 'DOORBELL_PASS') }}@{{ doorbell_address }}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64"
          roles:
            - detect
            - rtmp
    detect:
      width: 1280
      height: 720
