mqtt:
  host: "mqtt.lab.nkontur.com"
  user: mosquitto
  password: {{ lookup('env', 'MQTT_PASS') }}
  tls_ca_certs: /etc/ssl/certs/ISRG_Root_X1.pem
  tls_client_cert: /certs/nkontur.com/live/iot.lab.nkontur.com-0001/cert.pem
  tls_client_key: /certs/nkontur.com/live/iot.lab.nkontur.com-0001/privkey.pem
cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: "rtsp://admin:{{ lookup('env', 'DOORBELL_PASS') }}@{{ doorbell_address }}:554/cam/realmonitor?channel=1&subtype=0&authbasic=64"
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2560
      height: 1920
  back_door:
    ffmpeg:
      inputs:
        - path: "rtsp://admin:{{ lookup('env', 'REAR_CAMERA_PASS') }}@{{ back_camera_address }}:554/cam/realmonitor?channel=1&subtype=0"
          roles:
            - detect
            - rtmp
            - record
    detect:
      width: 2592
      height: 1944
record:
  enabled: True
  retain:
    days: 14
  events:
    retain:
      default: 100
detectors:
  tensorrt:
    type: tensorrt
    device: 0
objects:
  filters:
    person:
      threshold: .75
