- name: Install dependencies
  apt:
    name:
      - pulseaudio
    state: present
    update_cache: yes

- name: Template out pulseaudio system-wide service file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/base/systemd/pulseaudio.service' }}"
    dest: "/etc/systemd/system/pulseaudio.service"
    owner: root
    group: root
    mode: '0644'

- name: Make sure pulseaudio is started and enabled
  service:
    name: pulseaudio
    state: started
    enabled: yes
    daemon_reload: yes

- name: Replace before the expression till the begin of the file (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/pulse/system.pa
    regexp: '^load-module module-native-protocol-unix$'
    replace: 'load-module module-native-protocol-unix auth-anonymous=1'
  register: pulseaudio

- name: Remove line that causes suspension
  ansible.builtin.lineinfile:
    path: /etc/pulse/system.pa
    regexp: '^load-module module-suspend-on-idle$'
    state: absent
  register: pulseaudio_suspend

- name: Restart pulseaudio if config change
  service:
    name: pulseaudio
    state: restarted
  when: pulseaudio.changed or pulseaudio_suspend.changed

- name: Template out rhasspy entrypoint
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/docker/rhasspy/startup.sh' }}"
    dest: "{{ rhasspy_entrypoint_dest }}"
    owner: root
    group: root
    mode: '0744'

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/respeaker/seeed-voicecard.git'
    dest: /root/seed-voicecard
  when: is_respeaker
