- name: Install dependencies
  apt:
    name:
      - pulseaudio
      - pulseaudio-module-zeroconf
      - pulseaudio-module-bluetooth
    state: present
    update_cache: yes

- name: Set hostname on satellites
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"
  when: is_satellite

- name: Template out pulseaudio system-wide service file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/base/systemd/pulseaudio.service' }}"
    dest: "/etc/systemd/system/pulseaudio.service"
    owner: root
    group: root
    mode: '0644'

- name: Make sure pulseaudio is started and enabled
  service:
    name: pulseaudio
    state: started
    enabled: yes
    daemon_reload: yes

- name: Template out pulseaudio system-wide config file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/base/pulse/system.pa' }}"
    dest: "/etc/pulse/system.pa"
    owner: root
    group: root
    mode: '0644'
  register: pulseaudio
  when: not is_satellite

- name: Template out pulseaudio system-wide config file
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/base/pulse/system-satellite.pa' }}"
    dest: "/etc/pulse/system.pa"
    owner: root
    group: root
    mode: '0644'
  register: pulseaudio
  when: is_satellite

- name: Restart pulseaudio if config change
  service:
    name: pulseaudio
    state: restarted
  when: pulseaudio.changed

- name: Sets up cronjob to disable led lights
  ansible.builtin.cron:
    name: "Led disable"
    special_time: reboot
    job: "echo none > /sys/class/leds/led0/trigger && echo none > /sys/class/leds/led1/trigger"

- name: Template out rhasspy entrypoint
  ansible.builtin.template:
    src: "{{ lookup('env', 'CI_PROJECT_DIR') + '/docker/rhasspy/startup.sh' }}"
    dest: "{{ rhasspy_entrypoint_dest }}"
    owner: root
    group: root
    mode: '0744'

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/respeaker/seeed-voicecard.git'
    dest: /root/seed-voicecard
  when: is_respeaker
  register: respeaker

- name: Install respeaker drivers
  when: respeaker.changed
  ansible.builtin.command: chdir=/root/seed-voicecard ./install_arm64.sh

- name: Reboot when respeaker drivers installed
  ansible.builtin.reboot:
  when: respeaker.changed
