global:
  instanceName: "{{ location }}"
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: mqtts://mqtt.lab.nkontur.com:1883
  mqttOptions:
    username: mosquitto
    password: {{ lookup('env', 'MQTT_PASS') }}
bluetoothClassic:
  addresses:
    - 'E0:D0:83:4B:3F:84'

