global:
  instanceName: "{{ location }}"
  integrations:
    - homeAssistant
    - bluetoothClassic
homeAssistant:
  mqttUrl: mqtts://mqtt.lab.nkontur.com:1883
  mqttOptions:
    username: mosquitto
    password: {{ lookup('env', 'MQTT_PASS') }}
bluetoothClassic:
  addresses:
    - 'CO:D2:DD:33:43:0C'

